import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Providers from "@/components/Providers";
import { lazy, Suspense } from 'react';
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const PokeGridBackground = lazy(() => import("@/components/PokeGridBackground"));

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={null}>
          <PokeGridBackground />
        </Suspense>
        <Providers>
          <div className="min-h-screen">
            <Navbar />
            <main>
              {children}
            </main>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  )
}